global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus-metrics"
    scrape_interval: 1m
    static_configs:
      - targets: ['10.224.143.66:9090']
  - job_name: "node_exporter_metrics"
    scrape_interval: 1m
    static_configs:
      - targets: ['10.224.143.66:9100','10.224.143.55:9100','10.224.143.153:9100']
