- hosts: jenkins
  become: true
  tasks:
    - name: Install jenkins on top of docker
      shell: docker run -d --name jen -p 8080:8080 -p 50000:50000 -v jenkins_data:/var/jenkins_home jenkins/jenkins:lts
